name: 🐞 Application Issue Report
description: Report a issue in Streamer
labels: [bug]
body:

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: input
    id: streamer-version
    attributes:
      label: Streamer version
      description: |
        You can find your Streamer version in the **Settings** screen.
      placeholder: |
        Example: "1.2.6"
    validations:
      required: true

  - type: dropdown
    id: streamer_application
    attributes:
      label: Application
      description: Do you use Streamer iOS or tvOS?
      options:
        - iOS
        - tvOS

  - type: input
    id: ios-version
    attributes:
      label: iOS version
      description: |
        You can find this somewhere in your iOS settings.
      placeholder: |
        Example: "iOS 15.5"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.
